Pi-SP_sim: MyUserPhysicsList Class Reference
MyUserPhysicsList Class Reference
#include <physics.hh>
Public Member Functions
MyUserPhysicsList ()
~MyUserPhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructEM ()
virtual void ConstructProcess ()
void ContructGeneral ()
Private Attributes
G4MesonConstructor mConstructor
G4BosonConstructor boConstructor
G4BaryonConstructor baConstructor
Detailed Description
Definition at line 32 of file physics.hh.
Constructor & Destructor Documentation
MyUserPhysicsList()
MyUserPhysicsList::MyUserPhysicsList ()
Definition at line 16 of file physics.cc.
~MyUserPhysicsList()
MyUserPhysicsList::~MyUserPhysicsList ()
Definition at line 24 of file physics.cc.
Member Function Documentation
ConstructEM()
void MyUserPhysicsList::ConstructEM () virtual
Definition at line 43 of file physics.cc.
Referenced by ConstructProcess().
ConstructParticle()
void MyUserPhysicsList::ConstructParticle () virtual
Definition at line 28 of file physics.cc.
References baConstructor, boConstructor, and mConstructor.
ConstructProcess()
void MyUserPhysicsList::ConstructProcess () virtual
Definition at line 36 of file physics.cc.
References ConstructEM(), and ContructGeneral().
ContructGeneral()
void MyUserPhysicsList::ContructGeneral ()
Definition at line 58 of file physics.cc.
Referenced by ConstructProcess().
Member Data Documentation
baConstructor
G4BaryonConstructor MyUserPhysicsList::baConstructor private
Definition at line 47 of file physics.hh.
Referenced by ConstructParticle().
boConstructor
G4BosonConstructor MyUserPhysicsList::boConstructor private
Definition at line 46 of file physics.hh.
Referenced by ConstructParticle().
mConstructor
G4MesonConstructor MyUserPhysicsList::mConstructor private
Definition at line 45 of file physics.hh.
Referenced by ConstructParticle().
The documentation for this class was generated from the following files:
include/physics.hh
src/physics.cc