Pi-SP_sim: sim.cc File Reference
sim.cc File Reference
Main file.
#include <iostream>
#include "G4RunManager.hh"
#include "G4UImanager.hh"
#include "G4VisManager.hh"
#include "G4UIExecutive.hh"
#include "G4VisExecutive.hh"
#include "construct.hh"
#include "physics.hh"
#include "action.hh"
Classes
struct Configuration
Global struct to store usefull infos.
Functions
void PrintHelp ()
Prints the help message.
bool IsPositiveNumber (const char number[])
Checks if input is a natural number.
int main (int argc, const char **argv)
Main function.
Variables
Configuration gConfig
Detailed Description
Main file.
Author
Matteo Brini (brini.nosp@m.matt.nosp@m.eo@gm.nosp@m.ail..nosp@m.com)
Version
0.1
Date
2022-09-26
Copyright
Copyright (c) 2022
Definition in file sim.cc.
Function Documentation
IsPositiveNumber()
bool IsPositiveNumber (const char number[])
Checks if input is a natural number.
Parameters
number String you want to check.
Returns
true input can be a natural number.
false input cannot be a natural number.
Definition at line 81 of file sim.cc.
Referenced by main().
main()
int main (int argc, const char ** argv)
Main function.
Checks for user input flags, stores them in global variable gConfig. Controls for eventual errors. Executes the program based on the activated flags in gConfig.
Parameters
argc
argv
Returns
int
Definition at line 104 of file sim.cc.
References Configuration::beamOn, Configuration::gamma, gConfig, IsPositiveNumber(), Configuration::nEvents, PrintHelp(), and Configuration::vis.
PrintHelp()
void PrintHelp ()
Prints the help message.
This message is printed when -h flag or wrong input is passed to the program.
Definition at line 56 of file sim.cc.
Referenced by main().
Variable Documentation
gConfig
Configuration gConfig
Definition at line 49 of file sim.cc.
Referenced by main().